### ISSUE TITLE
Handling DateTimeOffset

### ISSUE THREAD

**Issue by carl-berg** [Spinit-AB/Spinit.CosmosDb#18]
Currently CosmosDB with default settings parses `DateTimeOffset`'s like `DateTime`, therefore losing the local timezone information. For example a value stored in cosmos like `2019-04-12T00:00:00+12:00` would be turned into a `DateTimeOffset` with the machine's local offset which would be `2019-04-11T14:00:00+02:00` on my machine.

**Comment by martin-oom** [comment]
Leaving this link for reference: [https://github.com/Azure/azure-cosmos-dotnet-v2/issues/235](https://github.com/Azure/azure-cosmos-dotnet-v2/issues/235)
