### ISSUE TITLE
Getting total count

### ISSUE THREAD

**Issue by martin-oom** [Spinit-AB/Spinit.CosmosDb#21]
Getting count was previously a very expensive operation in cosmos db (RU's). It seems like this is now free? If this is the case the warning in `ISearchRequest.IncludeTotalCount` can be removed.

**Comment by alveflo** [comment]
Hmm how come it's free?

**Comment by alveflo** [comment]
Turns out that this was free for just a period of time and now it's expensive again. I say we close this issue and leave the warning as is for now
