### ISSUE TITLE
UpsertAsync should not use v2 bulk

### ISSUE THREAD

**Issue by j82w** [Spinit-AB/Spinit.CosmosDb#46]
The UpsertAsync is using a new v2 bulk executor for each operations. Creating a new bulk executor is slow and has a lot of overhead because all the cache have to be reinitialized for each call and all the connections have to be recreated. 
 
https://github.com/Spinit-AB/Spinit.CosmosDb/blob/f817dba5b447367bec5fc4b4389a59338ba418c4/Spinit.CosmosDb/Internals/CosmosDbCollection.cs#L86-L105

Solution:
If upsert is only expected to have less than a few hundred items then just do the individual point reads. If there are thousands of records create a 2nd [CosmosClient singleton with bulk enabled](https://medium.com/@Ealsur/azure-cosmos-db-net-sql-sdk-bulk-support-9dea1d0ee023). Use the v3 bulk processing instead of the v2 SDK.

**Comment by carl-berg** [comment]
This is adressed in #51
