### ISSUE TITLE
CosmosClient singleton

### ISSUE THREAD

**Issue by j82w** [Spinit-AB/Spinit.CosmosDb#47]
1. Use a [CosmosClient singleton](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/best-practice-dotnet) for the application. Currently a CosmosClient is getting created per a database. There will eventually lead to networking issues and cause additional latency. The Cosmos SDK is very complex and has to initialize several caches before it is able to send requests.

https://github.com/Spinit-AB/Spinit.CosmosDb/blob/2d34585f24d066bc52b6b61c473e6b0eeedf7933/Spinit.CosmosDb/CosmosDatabase.cs#L58-L65

2. Remove v2 DocumentClient dependency. Having 2 SDK instances running causes unnecessary overhead. The v3 SDK should support all the scenarios of the v2 SDK. https://docs.microsoft.com/en-us/azure/cosmos-db/sql/migrate-dotnet-v2

**Comment by carl-berg** [comment]
1. The `CosmosDatabase` is meant to be a singleton in an application (which is how it is registered in the service collection if you use the `AddCosmosDatabase` extension to register it)
2. This will be adressed in #51

**Comment by carl-berg** [comment]
1. The `CosmosDatabase is meant to be a singleton in an application (which is how it is registered if you use the `AddCosmosDatabase` to register it)
2. This will be adressed in #51
